version = 0.1
[default.deploy.parameters]
stack_name = "module-02-users-sync"
resolve_s3 = true
s3_prefix = "module-02-users-sync"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "UserPoolAdminGroupName=\"apiAdmins\""
